spring:
  profiles:
    active: ${SHARE_PLATE_PROFILE}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        default_batch_fetch_size: 100
    open-in-view: false

  config:
    import: classpath:oauth.yml,classpath:s3.yml,classpath:rabbitmq.yml

logging.level:
  org:
    hibernate.SQL: debug
  com:
    amazonaws:
      util:
        EC2MetadataUtils: error
