spring:
  profiles:
    active: ${SHARE_PLATE_PROFILE}
    group:
      "dev": "rabbitmq-external,db-dev,feign-client-log,aws-credentials"
      "test": "rabbitmq-internal,db-dev,feign-client-log"
      "load": "rabbitmq-internal,db-load"
      "prod": "rabbitmq-external,db-prod,aws-credentials,save-log"
  config:
    import: classpath:rabbitmq.yml,classpath:oauth.yml,classpath:s3.yml,classpath:database.yml,classpath:log.yml
