cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: share-plate-s3
      mock.port: 8001
    stack:
      auto: false

file:
  upload:
    location:
      share: louie1se
      member: louie1se/member

---

spring:
  config:
    activate:
      on-profile: "aws-credentials"

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
